// Generated by CoffeeScript 1.7.1
$(document).on("click", "[data-menu]", function(e) {
  var menu;
  e.preventDefault();
  menu = $(this).data("menu");
  return renderMenu(menu);
});

$(document).on("click", "[data-button='close']", function(e) {
  e.preventDefault();
  return closeMenu();
});

$(document).on("click", "nav a[data-view]", function(e) {
  var view;
  e.preventDefault();
  view = $(this).data("view");
  $("nav a[data-view]").removeClass("selected");
  $(this).addClass("selected");
  renderView(view);
  return closeMenu();
});
