// Generated by CoffeeScript 1.7.1
$(document).on("click", "[data-menu]", function(e) {
  var menu;
  e.preventDefault();
  menu = $(this).data("menu");
  return renderMenu(menu);
});

$(document).on("click", "[data-button='close']", function(e) {
  e.preventDefault();
  return closeMenu();
});
