// Generated by CoffeeScript 1.7.1
$(document).on("click", "[data-menu]", function(e) {
  var menu;
  e.preventDefault();
  menu = $(this).data("menu");
  return renderMenu(menu);
});

$(document).on("click", ".navbar [data-view]", function(e) {
  var view;
  e.preventDefault();
  view = $(this).data("view");
  return changeFeedStyle(view);
});

$(document).on("click", "header [data-button='close']", function(e) {
  e.preventDefault();
  return closeMenu();
});

$(document).on("click", "nav a[data-view]", function(e) {
  var view;
  e.preventDefault();
  view = $(this).data("view");
  $("nav a[data-view]").removeClass("selected");
  $(this).addClass("selected");
  renderView(view);
  return closeMenu();
});

$(document).on("click", ".feed li", function(e) {
  var badge, index;
  e.preventDefault();
  index = $(this).data("index");
  badge = $(this).find("img").attr("src");
  return renderModal(index, badge);
});

$(document).on("click", ".modal [data-button='close']", function(e) {
  e.preventDefault();
  return closeModal();
});
