// Generated by CoffeeScript 1.7.1
var config, item;

config = {
  feeds: [
    item = {
      title: "CBS",
      url: "http://www.cbssports.com/partners/feeds/rss/nfl_news"
    }, item = {
      title: "NFL",
      url: "http://www.nfl.com/rss/rsslanding?searchString=home"
    }, item = {
      title: "Rotoworld",
      url: "http://www.rotoworld.com/rss/feed.aspx?sport=nfl&ftype=news&count=12&format=rss"
    }
  ],
  templates: {
    main: Handlebars.templates["main"]
  }
};
