// Generated by CoffeeScript 1.7.1
var loadFeeds, newsFeed;

newsFeed = {
  feeds: []
};

loadFeeds = function() {
  var i, _i, _ref, _results;
  _results = [];
  for (i = _i = 0, _ref = config.feeds.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    _results.push($.ajax({
      url: 'http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=10&callback=?&q=' + encodeURIComponent(config.feeds[i].url),
      dataType: 'json',
      success: function(data) {
        return newsFeed.feeds.push(data.responseData.feed);
      }
    }));
  }
  return _results;
};
