// Generated by CoffeeScript 1.7.1
var assembleFeeds, feed, loadFeeds;

feed = {
  temporary: [],
  feeds: []
};

loadFeeds = function() {
  var i, _i, _ref, _results;
  _results = [];
  for (i = _i = 0, _ref = config.feeds.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    _results.push($.ajax({
      url: 'http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=10&callback=?&q=' + encodeURIComponent(config.feeds[i].url),
      dataType: 'json',
      success: function(data) {
        return feed.temporary.push(data.responseData.feed);
      }
    }));
  }
  return _results;
};

assembleFeeds = function() {
  var i, k, parentCategory, _i, _j, _ref, _ref1;
  for (i = _i = 0, _ref = feed.temporary.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    parentCategory = feed.temporary[i].title;
    for (k = _j = 0, _ref1 = feed.temporary[i].entries.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; k = 0 <= _ref1 ? ++_j : --_j) {
      feed.temporary[i].entries[k].parent = parentCategory;
      feed.feeds.push(feed.temporary[i].entries[k]);
    }
  }
  return console.log(feed);
};
