// Generated by CoffeeScript 1.7.1
var assembleFeeds, feed, feedLoaded, finished, k, loadFeeds, resetFeeds;

feed = {
  temporary: [],
  feeds: []
};

k = 0;

finished = false;

feedLoaded = function() {
  console.log("========== Success ==========");
  k++;
  if (k === config.feeds.length) {
    return finished = true;
  }
};

loadFeeds = function() {
  var i, _i, _ref, _results;
  console.log("========== Load Feeds ==========");
  _results = [];
  for (i = _i = 0, _ref = config.feeds.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    _results.push($.ajax({
      url: 'http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=20&callback=?&q=' + encodeURIComponent(config.feeds[i].url),
      dataType: 'json',
      success: function(data, status, request) {
        feedLoaded();
        feed.temporary.push(data.responseData.feed);
        if (finished) {
          console.log("========== Finished ==========");
          return assembleFeeds();
        }
      }
    }));
  }
  return _results;
};

assembleFeeds = function() {
  var i, parentCategory, _i, _j, _ref, _ref1;
  console.log("========== Assemble Feeds ==========");
  for (i = _i = 0, _ref = feed.temporary.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    parentCategory = feed.temporary[i].title;
    for (k = _j = 0, _ref1 = feed.temporary[i].entries.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; k = 0 <= _ref1 ? ++_j : --_j) {
      feed.temporary[i].entries[k].parent = parentCategory;
      feed.feeds.push(feed.temporary[i].entries[k]);
    }
  }
  console.log(feed);
  renderFeed();
  setTimer(interval);
  return renderBadges();
};

resetFeeds = function() {
  feed.temporary = [];
  feed.feeds = [];
  k = 0;
  finished = false;
  return this.$el.find(".feed").empty();
};
