// Generated by CoffeeScript 1.7.1
var clearTimer, interval, setTimer, timer;

interval = null;

timer = null;

clearTimer = function() {
  return clearTimeout(timer);
};

setTimer = function(interval, timer) {
  interval = interval ? interval : this.$el.find(".feed").data("interval");
  return timer = setTimeout(function() {
    clearTimer();
    resetFeeds();
    return loadFeeds();
  }, interval);
};
