// Generated by CoffeeScript 1.7.1
var renderFeed, renderMain;

renderMain = function() {
  var template;
  template = config.templates.main;
  return this.$el.append(template);
};

renderFeed = function() {
  var template;
  template = config.templates.feed(feed);
  return this.$el.find(".feed").append(template);
};
