// Generated by CoffeeScript 1.7.1
var renderBadges, renderFeed, renderMain;

renderMain = function() {
  var template;
  template = config.templates.main;
  return this.$el.append(template);
};

renderFeed = function() {
  var template;
  template = config.templates.feed(feed);
  return this.$el.find(".feed").append(template);
};

renderBadges = function() {
  var i, item, k, res, str, _i, _ref, _results;
  console.log("========== Render Badges ==========");
  _results = [];
  for (i = _i = 0, _ref = feed.feeds.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    str = feed.feeds[i].content;
    _results.push((function() {
      var _j, _ref1, _results1;
      _results1 = [];
      for (k = _j = 0, _ref1 = teamList.teams.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; k = 0 <= _ref1 ? ++_j : --_j) {
        res = str.match(teamList.teams[k].shortname);
        if (res) {
          res = res[0].toLowerCase();
          item = this.$el.find("li[data-index=" + i + "]");
          _results1.push(item.find("img").attr("src", "../images/" + res + "/logo-001.png"));
        } else {
          _results1.push(void 0);
        }
      }
      return _results1;
    }).call(this));
  }
  return _results;
};
