// Generated by CoffeeScript 1.7.1
var team, teamList;

teamList = {
  teams: [
    team = {
      name: "Arizona Cardinals",
      shortname: "Cardinals",
      slug: "cardinals",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Atlanta Falcons",
      shortname: "Falcons",
      slug: "falcons",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Baltimore Ravens",
      shortname: "Ravens",
      slug: "ravens",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Buffalo Bills",
      shortname: "Bills",
      slug: "bills",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Carolina Panthers",
      shortname: "Panthers",
      slug: "panthers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Chicago Bears",
      shortname: "Bears",
      slug: "bears",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Cincinnati Bengals",
      shortname: "Bengals",
      slug: "bengals",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Cleveland Browns",
      shortname: "Browns",
      slug: "browns",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Dallas Cowboys",
      shortname: "Cowboys",
      slug: "cowboys",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Denver Broncos",
      shortname: "Broncos",
      slug: "broncos",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Detroit Lions",
      shortname: "Lions",
      slug: "lions",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Green Bay Packers",
      shortname: "Packers",
      slug: "packers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Houston Texans",
      shortname: "Texans",
      slug: "texans",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Indianapolis Colts",
      shortname: "Colts",
      slug: "colts",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Jacksonville Jaguars",
      shortname: "Jaguars",
      slug: "jaguars",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Kansas City Chiefs",
      shortname: "Chiefs",
      slug: "chiefs",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Miami Dolphins",
      shortname: "Dolphins",
      slug: "dolphins",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Minnesota Vikings",
      shortname: "Vikings",
      slug: "vikings",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New England Patriots",
      shortname: "Patriots",
      slug: "patriots",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New Orleans Saints",
      shortname: "Saints",
      slug: "saints",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New York Giants",
      shortname: "Giants",
      slug: "giants",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New York Jets",
      shortname: "Jets",
      slug: "jets",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Oakland Raiders",
      shortname: "Raiders",
      slug: "raiders",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Philadelphia Eagles",
      shortname: "Eagles",
      slug: "eagles",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Pittsburgh Steelers",
      shortname: "Steelers",
      slug: "steelers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Saint Louis Rams",
      shortname: "Rams",
      slug: "rams",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "San Diego Chargers",
      shortname: "Chargers",
      slug: "chargers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "San Francisco 49ers",
      shortname: "49ers",
      slug: "49ers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Seattle Seahawks",
      shortname: "Seahawks",
      slug: "seahawks",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Tampa Bay Buccaneers",
      shortname: "Buccaneers",
      slug: "buccaneers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Tennessee Titans",
      shortname: "Titans",
      slug: "titans",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Washington Redskins",
      shortname: "Redskins",
      slug: "redskins",
      logo: "logo-001.png",
      background: null
    }
  ]
};
