// Generated by CoffeeScript 1.7.1
var team, teamList;

teamList = {
  teams: [
    team = {
      name: "Arizona Cardinals",
      shortname: "Cardinals",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Atlanta Falcons",
      shortname: "Falcons",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Baltimore Ravens",
      shortname: "Ravens",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Buffalo Bills",
      shortname: "Bills",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Carolina Panthers",
      shortname: "Panthers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Chicago Bears",
      shortname: "Bears",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Cincinnati Bengals",
      shortname: "Bengals",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Cleveland Browns",
      shortname: "Browns",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Dallas Cowboys",
      shortname: "Cowboys",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Denver Broncos",
      shortname: "Broncos",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Detroit Lions",
      shortname: "Lions",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Green Bay Packers",
      shortname: "Packers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Houston Texans",
      shortname: "Texans",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Indianapolis Colts",
      shortname: "Colts",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Jacksonville Jaguars",
      shortname: "Jaguars",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Kansas City Chiefs",
      shortname: "Chiefs",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Miami Dolphins",
      shortname: "Dolphins",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Minnesota Vikings",
      shortname: "Vikings",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New England Patriots",
      shortname: "Patriots",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New Orleans Saints",
      shortname: "Saints",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New York Giants",
      shortname: "Giants",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "New York Jets",
      shortname: "Jets",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Oakland Raiders",
      shortname: "Raiders",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Philadelphia Eagles",
      shortname: "Eagles",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Pittsburgh Steelers",
      shortname: "Steelers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Saint Louis Rams",
      shortname: "Rams",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "San Diego Chargers",
      shortname: "Chargers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "San Francisco 49ers",
      shortname: "49ers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Seattle Seahawks",
      shortname: "Seahawks",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Tampa Bay Buccaneers",
      shortname: "Buccaneers",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Tennessee Titans",
      shortname: "Titans",
      logo: "logo-001.png",
      background: null
    }, team = {
      name: "Washington Redskins",
      shortname: "Redskins",
      logo: "logo-001.png",
      background: null
    }
  ]
};
